apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-with-name
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
#    server: "172.30.243.150"
    mount-options: "vers=4.1"
    server: "nfs-server.nfs.svc.cluster.local"
    path: "/exports"
